//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productData
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public string productDetails { get; set; }
        public string productImage { get; set; }
    }
}
