//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AdminSite.Models;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class RatnoTechEntities1 : DbContext
{
    public RatnoTechEntities1()
        : base("name=RatnoTechEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<productData> productDatas { get; set; }
}
